---
- name: Centreon | Get all mounted disk
  set_fact:
    centreon_disk_hosttemplate: "{{ centreon_disk_hosttemplate | default([]) | union([centreon_disk_hosttemplates_prefix + '-' + item.mount]) }}"
  with_items: "{{ ansible_mounts }}"
  when: >
    centreon_host_disk_detection
    and item.fstype in centreon_whitelist_fs
    and item.mount not in centreon_blacklist_mounts

- name: Centreon | Add disk monitoring
  become: False
  centreon_host:
    url: "{{ centreon_api_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    name: "{{ centreon_host_hostname | default(ansible_hostname) }}"
    hosttemplates: "{{ centreon_disk_hosttemplate }}"
    applycfg: "{{ centreon_applycfg | default(False) }}"
  delegate_to: "{{ centreon_delegate_to }}"
  notify: "centreon api applycfg"
